[workspace]
resolver = "2"
members = [
    "actions/post-comment",
    "actions/core",
]

[workspace.package]
version = "0.0.1"
edition = "2024"


[workspace.dependencies]
thiserror = "1"
octocrab = "0.47"
tokio = { version = "1", features = ["rt-multi-thread"] }
anyhow = "1"
